// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wusekilmebfbikwspiic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1c2VraWxtZWJmYmlrd3NwaWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA2MDIsImV4cCI6MjA2NTU0NjYwMn0.o12XMiCC7hASm5NiZ6jiqNAyfPa7YGcQvcGeN5aBBi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Bypass navigator.locks which can deadlock during JWT refresh,
    // causing all subsequent Supabase calls to hang silently.
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => {
      return await fn();
    },
  },
  global: {
    fetch: (url, options = {}) => {
      return fetch(url, {
        ...options,
        signal: options.signal || AbortSignal.timeout(30000), // 30 second timeout
      });
    },
  },
});